### ISSUE TITLE
plotConvergence: parameter names messed up with >10 parameters

### ISSUE THREAD

**Issue by soelderer** [danheck/TreeBUGS#12]
Hey!

I'm fitting a latent-trait model with 14 parameters and I've stumbled across an issue in plotConvergence.R.
Specifically, when investigating convergence I've noticed that the plots for the 10+th parameter were labelled in a weird way: with the names of two _other_ parameters concatenated (e.g. "C1C2" instead of "S").

Using `debug()`, I could trace the issue down to the `idx2name()` function in plotConvergence.R.
The simple `gsub()` command in the for-loop matches _every_ occurence of [1 including the one's in [10 [11 [12 etc.
Thus the weird double names.

A similar issue could emerge if parameter names are nested: say, you have a parameter "N" and other parameters "Npro", "Npre" etc.
Then, `name2idx()` would match _every_ occurence of "N", leading to troubles.
Other issues could probably emerge if parameter names end on numbers, say "C1".

Anyways, I figured it makes sense to match surrounding brackets and commas as well.
I already figured out a solution and tested the functions in isolation. I also tested it within the package, and it apparently fixed the issues. However, I have no experience with package building, so I can't test it thoroughly. I'll open a pull request, so I'd be glad if you could test it!

#13 

All the best,
Paul

**Comment by danheck** [comment]
Thanks a lot for reporting the bug and for the solution. I will look into this the next days. 
Best, Daniel

**Comment by danheck** [comment]
Thanks again for the bug fix. I committed this and will test it again, but this looks all good.

**Comment by soelderer** [comment]
You're welcome! Thanks for the quick merge.
