### ISSUE TITLE
Cannot extract samples of individual-level parameters: getSamples, parameter argument for "theta" no longer works

### ISSUE THREAD

**Issue by JacobElder** [danheck/TreeBUGS#9]
Hi,

I believe I was using this in a previous R version and it was working. I revisited TreeBugs and now when I use the following argument.

`getSamples(fittedModel, parameter = "theta")`

Returns the following error:

`Error in `[.default`(x[[k]], , j, drop = drop) : subscript out of bounds`

This prevents me from extracting all individual-level parameters. I believe this is a recent issue.

**Comment by danheck** [comment]
Thanks for bringing up this issue and thanks to @mariusbarth for fixing it!
